version: "3"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=tjCfqFcxXJYnERaDlLrtgyVehfhKWGoe
      - DATABASE_NAME=application
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
    networks:
      - application-network
    depends_on:
      - database

  database:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=application
      - MYSQL_ROOT_PASSWORD=tjCfqFcxXJYnERaDlLrtgyVehfhKWGoe
    volumes:
      - application-database:/var/lib/mysql
    networks:
      - application-network

volumes:
  application-database:

networks:
  application-network:
    driver: bridge